import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  Alert,
} from 'react-native';
import { Stack, useRouter, useLocalSearchParams } from 'expo-router';
import DateTimePicker from '@react-native-community/datetimepicker';

// Import storage services
import { recordStorage } from '@/src/services/record-storage';
import { type DataRecord, TemplateFieldType } from '@/src/types/data-collection';

// Import StyleSheet
import { StyleSheet } from 'react-native';

export default function CreateRecordScreen() {
  const router = useRouter();
  const { projectId } = useLocalSearchParams();

  // Form state
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [value, setValue] = useState<string>('');
  const [status, setStatus] = useState<'pending' | 'completed'>('pending');
  const [templateId, setTemplateId] = useState<string>('');
  const [showDatePicker, setShowDatePicker] = useState(false);
  const [dateValue, setDateValue] = useState(new Date());

  // Project info for template selection
  const [project, setProject] = useState<any>(null);
  const [availableTemplates, setAvailableTemplates] = useState<any[]>([]);

  React.useEffect(() => {
    loadProjectAndTemplates();
  }, [projectId]);

  const loadProjectAndTemplates = async () => {
    try {
      // Load project details
      const projectData = await import('@/src/services/project-storage').then(m => m.projectStorage.getById(projectId as string));
      
      if (projectData) {
        setProject(projectData);

        // Get available templates for this project
        const templates = await import('@/src/services/template-storage').then(m => m.templateStorage.getAll());
        
        // Filter templates that belong to this project or are global
        const projectTemplates = templates.filter(t => 
          t.projectId === projectId || !t.projectId // Global templates (no projectId) available to all projects
        );
        
        setAvailableTemplates(projectTemplates);
      }
    } catch (error) {
      console.error('Error loading project:', error);
    }
  };

  const handleSelectTemplate = async (template: any) => {
    setTemplateId(template.id);
    
    // Optionally pre-fill fields based on template structure
    if (template.fields) {
      // Could auto-populate form fields from template here
    }
  };

  const handleSubmit = async () => {
    if (!name.trim()) {
      Alert.alert('Validation Error', 'Please enter a name for this record');
      return;
    }

    try {
      // Create the record
      const newRecord: DataRecord = {
        id: '', // Will be generated by storage
        projectId: projectId as string,
        templateId: templateId || undefined,
        name: name.trim(),
        description: description.trim() || undefined,
        value: value !== '' ? parseFloat(value) : undefined,
        status,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      // Save to storage
      const savedRecord = await recordStorage.create(newRecord);

      // Navigate to view screen
      router.push({
        pathname: '/data-collection/[recordId]/view',
        params: { recordId: savedRecord.id },
      });
      
    } catch (error) {
      console.error('Error creating record:', error);
      Alert.alert('Error', 'Failed to create record. Please try again.');
    }
  };

  const handleDateChange = (_event: any, selectedDate?: Date) => {
    if (selectedDate) {
      setDateValue(selectedDate);
      setShowDatePicker(false);
    }
  };

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      keyboardVerticalOffset={Platform.OS === 'ios' ? 90 : 0}
      style={{ flex: 1, backgroundColor: '#ffffff' }}
    >
      <ScrollView 
        contentContainerStyle={{ flexGrow: 1, padding: 24 }}
        showsVerticalScrollIndicator={false}
      >
        <Stack.Screen 
          options={{
            title: 'Create Record',
            headerBackTitle: 'Back',
          }}
        />

        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>New Record</Text>
          <Text style={styles.headerSubtitle}>Fill in the details below</Text>
        </View>

        {/* Template Selection (if available) */}
        {availableTemplates.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Select Template</Text>
            
            <ScrollView 
              horizontal 
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={styles.templateScrollContainer}
            >
              {availableTemplates.map(template => (
                <TouchableOpacity
                  key={template.id}
                  style={[
                    styles.templateCard,
                    templateId === template.id && styles.selectedTemplate
                  ]}
                  onPress={() => handleSelectTemplate(template)}
                >
                  <View style={styles.templateHeader}>
                    <Text style={[
                      styles.templateName,
                      templateId === template.id && styles.selectedTemplateName
                    ]}>
                      {template.name}
                    </Text>
                  </View>
                  
                  {template.description && (
                    <Text style={styles.templateDescription} numberOfLines={2}>
                      {template.description}
                    </Text>
                  )}

                  {template.version && (
                    <View style={styles.versionBadge}>
                      <Text style={styles.versionText}>v{template.version}</Text>
                    </View>
                  )}
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>
        )}

        {/* Basic Fields */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Basic Information</Text>
          
          {/* Name */}
          <View style={styles.inputGroup}>
            <Text style={styles.label}>Name *</Text>
            <TextInput
              style={[styles.input, name.length > 0 && styles.inputValid]}
              placeholder="Record name"
              placeholderTextColor="#9ca3af"
              value={name}
              onChangeText={setName}
              onSubmitEditing={() => {} // Could navigate to description
            }
            />
          </View>

          {/* Description */}
          <View style={styles.inputGroup}>
            <Text style={styles.label}>Description</Text>
            <TextInput
              style={[styles.textAreaInput, description.length > 0 && styles.inputValid]}
              placeholder="Optional description"
              placeholderTextColor="#9ca3af"
              value={description}
              onChangeText={setDescription}
              multiline
              numberOfLines={4}
            />
          </View>

          {/* Value */}
          <View style={styles.inputGroup}>
            <Text style={styles.label}>Value (Optional)</Text>
            <TextInput
              style={[styles.input, value.length > 0 && styles.inputValid]}
              placeholder="Enter numeric value"
              placeholderTextColor="#9ca3af"
              value={value}
              onChangeText={setValue}
              keyboardType="numeric"
            />
          </View>

          {/* Status */}
          <View style={styles.inputGroup}>
            <Text style={styles.label}>Status</Text>
            <View style={styles.statusButtonsContainer}>
              <TouchableOpacity
                style={[
                  styles.statusButton,
                  status === 'pending' ? styles.activeStatus : styles.inactiveStatus,
                ]}
                onPress={() => setStatus('pending')}
              >
                <Text 
                  style={[
                    styles.statusButtonText,
                    status === 'pending' && styles.activeStatusText,
                  ]}
                >
                  Pending
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[
                  styles.statusButton,
                  status === 'completed' ? styles.activeStatus : styles.inactiveStatus,
                ]}
                onPress={() => setStatus('completed')}
              >
                <Text 
                  style={[
                    styles.statusButtonText,
                    status === 'completed' && styles.activeStatusText,
                  ]}
                >
                  Completed
                </Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Date */}
          <View style={styles.inputGroup}>
            <Text style={styles.label}>Created Date</Text>
            <TouchableOpacity 
              style={styles.dateButton}
              onPress={() => setShowDatePicker(true)}
            >
              <Text style={styles.dateButtonText}>
                {dateValue.toLocaleDateString()}
              </Text>
            </TouchableOpacity>

            {showDatePicker && (
              <DateTimePicker
                value={dateValue}
                mode="date"
                display={Platform.OS === 'ios' ? 'spinner' : 'default'}
                onChange={handleDateChange}
              />
            )}
          </View>
        </View>

        {/* Action Buttons */}
        <View style={styles.actionsContainer}>
          <TouchableOpacity 
            style={[styles.cancelButton, { backgroundColor: '#e5e7eb' }]}
            onPress={() => router.back()}
          >
            <Text style={styles.cancelButtonText}>Cancel</Text>
          </TouchableOpacity>

          <TouchableOpacity 
            style={[styles.saveButton, { shadowColor: '#3b82f6', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8 }]}
            onPress={handleSubmit}
          >
            <Text style={styles.saveButtonText}>Create Record</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const baseInput = {
  backgroundColor: '#f9fafb',
  borderRadius: 10,
  paddingVertical: 12,
  paddingHorizontal: 16,
  fontSize: 16,
  color: '#1f2937',
  borderWidth: 1,
  borderColor: '#e5e7eb',
};

const styles = StyleSheet.create({
  header: { marginBottom: 24 },
  headerTitle: { fontSize: 32, fontWeight: 'bold', color: '#1e293b' },
  headerSubtitle: { fontSize: 16, color: '#6b7280', marginTop: 4 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '600', color: '#374151', marginBottom: 12 },
  inputGroup: { marginBottom: 16 },
  label: { fontSize: 14, fontWeight: '500', color: '#374151', marginBottom: 8 },
  input: baseInput,
  inputValid: { backgroundColor: '#ecfdf5', borderColor: '#86efac' },
  textAreaInput: {
    ...baseInput,
    minHeight: 100,
    paddingTop: 14,
  },
  templateScrollContainer: { 
    flexDirection: 'row', 
    gap: 12, 
    paddingBottom: 8, 
    paddingRight: 16,
  },
  templateCard: {
    flex: 1, // Changed from 0.8 to handle horizontal scrolling better
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 14,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  selectedTemplate: {
    borderColor: '#3b82f6',
    backgroundColor: '#eff6ff',
  },
  templateHeader: { marginBottom: 8 },
  templateName: { fontSize: 14, fontWeight: '600', color: '#1f2937' },
  selectedTemplateName: { color: '#3b82f6' },
  templateDescription: { 
    fontSize: 12, 
    color: '#6b7280',
    lineHeight: 14,
  },
versionBadge: {
    marginTop: -4,
    marginBottom: -8,
    marginLeft: 'auto', // Fixed: was 'auto' without quotes
    backgroundColor: '#3b82f6',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  versionText: { color: 'white', fontSize: 9, fontWeight: '600' },
  statusButtonsContainer: { flexDirection: 'row', gap: 8 },
  statusButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'center',
  },
  activeStatus: {
    backgroundColor: '#dcfce7',
    borderColor: '#86efac',
  },
  inactiveStatus: {
    backgroundColor: '#f3f4f6',
    borderColor: '#e5e7eb',
  },
  statusButtonText: { color: '#374151' },
  activeStatusText: { color: '#065f46', fontWeight: '600' },
  dateButton: {
    backgroundColor: '#f9fafb',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'center',
  },
  dateButtonText: { color: '#374151', fontSize: 14 },
  actionsContainer: {
    flexDirection: 'row',
    marginTop: 20,
    gap: 12,
    paddingBottom: 20,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  cancelButtonText: { color: '#374151', fontSize: 16, fontWeight: '600' },
  saveButton: {
    flex: 2,
    backgroundColor: '#3b82f6',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  saveButtonText: { color: 'white', fontSize: 16, fontWeight: '700' },
});
